### ISSUE TITLE
AttributeError: 'DatasetAGOL' object has no attribute 'days_since_last_data_change'

### ISSUE THREAD

**Issue by CJuice** [CJuice/Data-Freshness#3]
Error Message: Traceback (most recent call last):
  File "D:\DateFreshness\Scripts\doit_DataFreshness_MainProcess_AGOL.py", line 232, in <module>
    main()
  File "D:\DateFreshness\Scripts\doit_DataFreshness_MainProcess_AGOL.py", line 128, in main
    agol_dataset.is_up_to_date()
  File "D:\DateFreshness\Scripts\doit_DataFreshness_DatasetAGOL.py", line 439, in is_up_to_date
    if int_check is not None and self.days_since_last_data_change is not None:
AttributeError: 'DatasetAGOL' object has no attribute 'days_since_last_data_change'
Exception in Task: System.Exception: Non zero exit code
Exit code (1) description: Incorrect function.

**Comment by CJuice** [comment]
discovered that a previous attribute name self.days_since_last_data_change was still referenced in the code despite the class attribute being refactored to self.days_since_most_recent_data_change Problem didn't surface until today assuming because agol asset changed and that uncovered issue. Refactored to remove old reference and be consistent. Code ran successfully.
